/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Tommy Hendricks
 */
public class MainScreenWin extends javax.swing.JFrame {
    private UI.PlayerProfileWin ppw;
    private UI.TypeSomethingVinillaRaceWin vr;
    /**
     * Creates new form MainScreenWin
     */
    public MainScreenWin() {
        ppw = new PlayerProfileWin(this);
        ppw.setVisible(false);
        ppw.setTitle("User Profile_");
        ppw.setLocationRelativeTo(null);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        TypeSomethingTitleLabel = new javax.swing.JLabel();
        profileButton = new javax.swing.JButton();
        TypeSomethingBasicRace = new javax.swing.JButton();
        RaceIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TypeSomethingCheckpoint = new javax.swing.JButton();
        TypeSomethingInstantDeath = new javax.swing.JButton();
        RaceIcon1 = new javax.swing.JLabel();
        RaceIcon2 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setForeground(new java.awt.Color(0, 51, 51));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        TypeSomethingTitleLabel.setFont(new java.awt.Font("Yu Gothic Light", 0, 48)); // NOI18N
        TypeSomethingTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TypeSomethingTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TypeSomethingTitleLabel.setText("Type Something_");

        profileButton.setBackground(new java.awt.Color(153, 153, 153));
        profileButton.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        profileButton.setText("Profile");
        profileButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        TypeSomethingBasicRace.setBackground(new java.awt.Color(153, 153, 153));
        TypeSomethingBasicRace.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        TypeSomethingBasicRace.setText("Race");
        TypeSomethingBasicRace.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        TypeSomethingBasicRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeSomethingBasicRaceActionPerformed(evt);
            }
        });

        RaceIcon.setText("Race Icon");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stats.png"))); // NOI18N

        TypeSomethingCheckpoint.setBackground(new java.awt.Color(153, 153, 153));
        TypeSomethingCheckpoint.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        TypeSomethingCheckpoint.setText("Checkpoint");
        TypeSomethingCheckpoint.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        TypeSomethingCheckpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeSomethingCheckpointActionPerformed(evt);
            }
        });

        TypeSomethingInstantDeath.setBackground(new java.awt.Color(153, 153, 153));
        TypeSomethingInstantDeath.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        TypeSomethingInstantDeath.setText("Instant Death");
        TypeSomethingInstantDeath.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        TypeSomethingInstantDeath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeSomethingInstantDeathActionPerformed(evt);
            }
        });

        RaceIcon1.setText("Race Icon");

        RaceIcon2.setText("Race Icon");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(TypeSomethingTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(RaceIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TypeSomethingBasicRace, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RaceIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TypeSomethingCheckpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(RaceIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TypeSomethingInstantDeath, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(346, 346, 346))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TypeSomethingTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RaceIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TypeSomethingBasicRace, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeSomethingInstantDeath, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RaceIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeSomethingCheckpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RaceIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TypeSomethingBasicRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeSomethingBasicRaceActionPerformed
        vr = new TypeSomethingVinillaRaceWin(this);
        vr.setLocationRelativeTo(null);
        vr.setTitle("TypeSomething_Vanilla Race");
        this.setVisible(false);
        vr.setVisible(true);
    }//GEN-LAST:event_TypeSomethingBasicRaceActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        this.setVisible(false);
        ppw.setVisible(true);
    }//GEN-LAST:event_profileButtonActionPerformed

    private void TypeSomethingCheckpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeSomethingCheckpointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeSomethingCheckpointActionPerformed

    private void TypeSomethingInstantDeathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeSomethingInstantDeathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeSomethingInstantDeathActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RaceIcon;
    private javax.swing.JLabel RaceIcon1;
    private javax.swing.JLabel RaceIcon2;
    private javax.swing.JButton TypeSomethingBasicRace;
    private javax.swing.JButton TypeSomethingCheckpoint;
    private javax.swing.JButton TypeSomethingInstantDeath;
    private javax.swing.JLabel TypeSomethingTitleLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton profileButton;
    // End of variables declaration//GEN-END:variables
}
