/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import com.google.gson.Gson;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowFocusListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import main.PlayerData;

/**
 *
 * @author Tommy Hendricks
 */
public class PlayerProfileWin extends javax.swing.JFrame {
    private MainScreenWin mw;
    private PlayerData pd;
    private JFileChooser chooser;
    private WindowFocusListener we;
    /**
     * Creates new form PlayerProfileWin
     */
    public PlayerProfileWin(MainScreenWin mw) {
       this.mw = mw;
       pd = PlayerData.getInstance();
       
       initComponents();
       
       chooser = new JFileChooser();
       
    }
    
    /**
     * This will update all of the info in the player profile window
     * The reason this is public is because it is being used in a window listener
     * outside of the class.
     */
    public void updateAllData(){
        allTimePrompts.setText(String.valueOf(pd.getAllTimePrompts()));
        allTimeFastest.setText(String.valueOf(pd.getAllTimeTopWpm()));
        allTimeAvgErrors.setText(String.valueOf(pd.getAllTimeAvgError()));
        allTimeAvgWpm.setText(String.valueOf(pd.getAllTimeAvgWpm()));
        
        vrTotalPrompts.setText(String.valueOf(pd.getVrAllTimePrompts()));
        vrAvgWPM.setText(String.valueOf(pd.getVrAvgWpm()));
        vrAvgErrors.setText(String.valueOf(pd.getVrAvgErrors()));
        vrFastestWPM.setText(String.valueOf(pd.getVrAllFastestWPM()));
        
        idTotalPrompts.setText(String.valueOf(pd.getIdAllTimePrompts()));
        idAvgWPM.setText(String.valueOf(pd.getIdAvgWpm()));
        idAvgErrors.setText(String.valueOf(pd.getIdAvgErrors()));
        idFastestWPM.setText(String.valueOf(pd.getIdAllFastestWPM()));

        usernameLabel.setText(pd.getUsername());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        allTimeAvgWpmLabel = new javax.swing.JLabel();
        allTimeAvgWpm = new javax.swing.JLabel();
        TotalPromptsPannel = new javax.swing.JPanel();
        totalPrompts = new javax.swing.JLabel();
        allTimePrompts = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        allTimeAvgLabel3 = new javax.swing.JLabel();
        allTimeFastest = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TotalPromptsPannel2 = new javax.swing.JPanel();
        vrAvgSpeedLabel = new javax.swing.JLabel();
        vrTotalPrompts = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        vinilaRaceLabel = new javax.swing.JLabel();
        TotalPromptsPannel3 = new javax.swing.JPanel();
        AvgSpeedLabel1 = new javax.swing.JLabel();
        vrAvgWPM = new javax.swing.JLabel();
        TotalPromptsPannel4 = new javax.swing.JPanel();
        AvgSpeedLabel2 = new javax.swing.JLabel();
        vrAvgErrors = new javax.swing.JLabel();
        TotalPromptsPannel5 = new javax.swing.JPanel();
        AvgSpeedLabel3 = new javax.swing.JLabel();
        vrFastestWPM = new javax.swing.JLabel();
        vinilaRaceLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        TotalPromptsPannel6 = new javax.swing.JPanel();
        idAvgSpeedLabel1 = new javax.swing.JLabel();
        idTotalPrompts = new javax.swing.JLabel();
        TotalPromptsPannel7 = new javax.swing.JPanel();
        AvgSpeedLabel4 = new javax.swing.JLabel();
        idAvgWPM = new javax.swing.JLabel();
        TotalPromptsPannel8 = new javax.swing.JPanel();
        AvgSpeedLabel5 = new javax.swing.JLabel();
        idAvgErrors = new javax.swing.JLabel();
        TotalPromptsPannel9 = new javax.swing.JPanel();
        AvgSpeedLabel6 = new javax.swing.JLabel();
        idFastestWPM = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        allTimeAvgLabel2 = new javax.swing.JLabel();
        allTimeAvgErrors = new javax.swing.JLabel();
        changeUsernameButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        saveButton = new javax.swing.JMenuItem();
        loadButton = new javax.swing.JMenuItem();

        label1.setText("label1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        usernameLabel.setFont(new java.awt.Font("Yu Gothic Light", 0, 36)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("N/A");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(175, 115));

        allTimeAvgWpmLabel.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        allTimeAvgWpmLabel.setForeground(new java.awt.Color(255, 255, 255));
        allTimeAvgWpmLabel.setText("All Time Avg WPM");

        allTimeAvgWpm.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        allTimeAvgWpm.setForeground(new java.awt.Color(255, 255, 255));
        allTimeAvgWpm.setText("N/A");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(allTimeAvgWpm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(allTimeAvgWpmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allTimeAvgWpmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allTimeAvgWpm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TotalPromptsPannel.setBackground(new java.awt.Color(0, 0, 0));
        TotalPromptsPannel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        TotalPromptsPannel.setPreferredSize(new java.awt.Dimension(175, 115));

        totalPrompts.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        totalPrompts.setForeground(new java.awt.Color(255, 255, 255));
        totalPrompts.setText("Total Prompts");

        allTimePrompts.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        allTimePrompts.setForeground(new java.awt.Color(255, 255, 255));
        allTimePrompts.setText("N/A");

        javax.swing.GroupLayout TotalPromptsPannelLayout = new javax.swing.GroupLayout(TotalPromptsPannel);
        TotalPromptsPannel.setLayout(TotalPromptsPannelLayout);
        TotalPromptsPannelLayout.setHorizontalGroup(
            TotalPromptsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TotalPromptsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allTimePrompts, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPrompts, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        TotalPromptsPannelLayout.setVerticalGroup(
            TotalPromptsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalPrompts, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allTimePrompts)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        allTimeAvgLabel3.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        allTimeAvgLabel3.setForeground(new java.awt.Color(255, 255, 255));
        allTimeAvgLabel3.setText("Fastest WPM");

        allTimeFastest.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        allTimeFastest.setForeground(new java.awt.Color(255, 255, 255));
        allTimeFastest.setText("N/A");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allTimeFastest, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allTimeAvgLabel3))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allTimeAvgLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allTimeFastest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TotalPromptsPannel2.setBackground(new java.awt.Color(0, 0, 0));
        TotalPromptsPannel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        vrAvgSpeedLabel.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        vrAvgSpeedLabel.setForeground(new java.awt.Color(255, 255, 255));
        vrAvgSpeedLabel.setText("Total Prompts");

        vrTotalPrompts.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        vrTotalPrompts.setForeground(new java.awt.Color(255, 255, 255));
        vrTotalPrompts.setText("N/A");

        javax.swing.GroupLayout TotalPromptsPannel2Layout = new javax.swing.GroupLayout(TotalPromptsPannel2);
        TotalPromptsPannel2.setLayout(TotalPromptsPannel2Layout);
        TotalPromptsPannel2Layout.setHorizontalGroup(
            TotalPromptsPannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TotalPromptsPannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vrTotalPrompts, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vrAvgSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        TotalPromptsPannel2Layout.setVerticalGroup(
            TotalPromptsPannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vrAvgSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vrTotalPrompts)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        vinilaRaceLabel.setFont(new java.awt.Font("Yu Gothic", 0, 36)); // NOI18N
        vinilaRaceLabel.setForeground(new java.awt.Color(255, 255, 255));
        vinilaRaceLabel.setText("Vanilla Race");

        TotalPromptsPannel3.setBackground(new java.awt.Color(0, 0, 0));
        TotalPromptsPannel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        TotalPromptsPannel3.setPreferredSize(new java.awt.Dimension(167, 123));

        AvgSpeedLabel1.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        AvgSpeedLabel1.setForeground(new java.awt.Color(255, 255, 255));
        AvgSpeedLabel1.setText("Avg WPM");

        vrAvgWPM.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        vrAvgWPM.setForeground(new java.awt.Color(255, 255, 255));
        vrAvgWPM.setText("N/A");

        javax.swing.GroupLayout TotalPromptsPannel3Layout = new javax.swing.GroupLayout(TotalPromptsPannel3);
        TotalPromptsPannel3.setLayout(TotalPromptsPannel3Layout);
        TotalPromptsPannel3Layout.setHorizontalGroup(
            TotalPromptsPannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TotalPromptsPannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vrAvgWPM, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AvgSpeedLabel1))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        TotalPromptsPannel3Layout.setVerticalGroup(
            TotalPromptsPannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AvgSpeedLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vrAvgWPM)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        TotalPromptsPannel4.setBackground(new java.awt.Color(0, 0, 0));
        TotalPromptsPannel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        AvgSpeedLabel2.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        AvgSpeedLabel2.setForeground(new java.awt.Color(255, 255, 255));
        AvgSpeedLabel2.setText("Avg Errors");

        vrAvgErrors.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        vrAvgErrors.setForeground(new java.awt.Color(255, 255, 255));
        vrAvgErrors.setText("N/A");

        javax.swing.GroupLayout TotalPromptsPannel4Layout = new javax.swing.GroupLayout(TotalPromptsPannel4);
        TotalPromptsPannel4.setLayout(TotalPromptsPannel4Layout);
        TotalPromptsPannel4Layout.setHorizontalGroup(
            TotalPromptsPannel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TotalPromptsPannel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vrAvgErrors, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AvgSpeedLabel2))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        TotalPromptsPannel4Layout.setVerticalGroup(
            TotalPromptsPannel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AvgSpeedLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vrAvgErrors)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        TotalPromptsPannel5.setBackground(new java.awt.Color(0, 0, 0));
        TotalPromptsPannel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        AvgSpeedLabel3.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        AvgSpeedLabel3.setForeground(new java.awt.Color(255, 255, 255));
        AvgSpeedLabel3.setText("Fastest WPM");

        vrFastestWPM.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        vrFastestWPM.setForeground(new java.awt.Color(255, 255, 255));
        vrFastestWPM.setText("N/A");

        javax.swing.GroupLayout TotalPromptsPannel5Layout = new javax.swing.GroupLayout(TotalPromptsPannel5);
        TotalPromptsPannel5.setLayout(TotalPromptsPannel5Layout);
        TotalPromptsPannel5Layout.setHorizontalGroup(
            TotalPromptsPannel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TotalPromptsPannel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TotalPromptsPannel5Layout.createSequentialGroup()
                        .addComponent(vrFastestWPM, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(AvgSpeedLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addContainerGap())
        );
        TotalPromptsPannel5Layout.setVerticalGroup(
            TotalPromptsPannel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AvgSpeedLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vrFastestWPM)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        vinilaRaceLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 36)); // NOI18N
        vinilaRaceLabel1.setForeground(new java.awt.Color(255, 255, 255));
        vinilaRaceLabel1.setText("Instant Death");

        TotalPromptsPannel6.setBackground(new java.awt.Color(0, 0, 0));
        TotalPromptsPannel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        idAvgSpeedLabel1.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        idAvgSpeedLabel1.setForeground(new java.awt.Color(255, 255, 255));
        idAvgSpeedLabel1.setText("Total Prompts");

        idTotalPrompts.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        idTotalPrompts.setForeground(new java.awt.Color(255, 255, 255));
        idTotalPrompts.setText("N/A");

        javax.swing.GroupLayout TotalPromptsPannel6Layout = new javax.swing.GroupLayout(TotalPromptsPannel6);
        TotalPromptsPannel6.setLayout(TotalPromptsPannel6Layout);
        TotalPromptsPannel6Layout.setHorizontalGroup(
            TotalPromptsPannel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TotalPromptsPannel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTotalPrompts, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idAvgSpeedLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        TotalPromptsPannel6Layout.setVerticalGroup(
            TotalPromptsPannel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idAvgSpeedLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTotalPrompts)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TotalPromptsPannel7.setBackground(new java.awt.Color(0, 0, 0));
        TotalPromptsPannel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        AvgSpeedLabel4.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        AvgSpeedLabel4.setForeground(new java.awt.Color(255, 255, 255));
        AvgSpeedLabel4.setText("Avg WPM");

        idAvgWPM.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        idAvgWPM.setForeground(new java.awt.Color(255, 255, 255));
        idAvgWPM.setText("N/A");

        javax.swing.GroupLayout TotalPromptsPannel7Layout = new javax.swing.GroupLayout(TotalPromptsPannel7);
        TotalPromptsPannel7.setLayout(TotalPromptsPannel7Layout);
        TotalPromptsPannel7Layout.setHorizontalGroup(
            TotalPromptsPannel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TotalPromptsPannel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idAvgWPM, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AvgSpeedLabel4))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        TotalPromptsPannel7Layout.setVerticalGroup(
            TotalPromptsPannel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AvgSpeedLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idAvgWPM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TotalPromptsPannel8.setBackground(new java.awt.Color(0, 0, 0));
        TotalPromptsPannel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        AvgSpeedLabel5.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        AvgSpeedLabel5.setForeground(new java.awt.Color(255, 255, 255));
        AvgSpeedLabel5.setText("Avg Errors");

        idAvgErrors.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        idAvgErrors.setForeground(new java.awt.Color(255, 255, 255));
        idAvgErrors.setText("N/A");

        javax.swing.GroupLayout TotalPromptsPannel8Layout = new javax.swing.GroupLayout(TotalPromptsPannel8);
        TotalPromptsPannel8.setLayout(TotalPromptsPannel8Layout);
        TotalPromptsPannel8Layout.setHorizontalGroup(
            TotalPromptsPannel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TotalPromptsPannel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idAvgErrors, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AvgSpeedLabel5))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        TotalPromptsPannel8Layout.setVerticalGroup(
            TotalPromptsPannel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AvgSpeedLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idAvgErrors)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TotalPromptsPannel9.setBackground(new java.awt.Color(0, 0, 0));
        TotalPromptsPannel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        AvgSpeedLabel6.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        AvgSpeedLabel6.setForeground(new java.awt.Color(255, 255, 255));
        AvgSpeedLabel6.setText("Fastest WPM");

        idFastestWPM.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        idFastestWPM.setForeground(new java.awt.Color(255, 255, 255));
        idFastestWPM.setText("N/A");

        javax.swing.GroupLayout TotalPromptsPannel9Layout = new javax.swing.GroupLayout(TotalPromptsPannel9);
        TotalPromptsPannel9.setLayout(TotalPromptsPannel9Layout);
        TotalPromptsPannel9Layout.setHorizontalGroup(
            TotalPromptsPannel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TotalPromptsPannel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TotalPromptsPannel9Layout.createSequentialGroup()
                        .addComponent(idFastestWPM, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(AvgSpeedLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addContainerGap())
        );
        TotalPromptsPannel9Layout.setVerticalGroup(
            TotalPromptsPannel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPromptsPannel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AvgSpeedLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idFastestWPM)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel4.setPreferredSize(new java.awt.Dimension(175, 115));

        allTimeAvgLabel2.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        allTimeAvgLabel2.setForeground(new java.awt.Color(255, 255, 255));
        allTimeAvgLabel2.setText("All Time Avg Errors");

        allTimeAvgErrors.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        allTimeAvgErrors.setForeground(new java.awt.Color(255, 255, 255));
        allTimeAvgErrors.setText("N/A");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(allTimeAvgErrors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(allTimeAvgLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allTimeAvgLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allTimeAvgErrors)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        changeUsernameButton.setForeground(new java.awt.Color(0, 0, 0));
        changeUsernameButton.setText("Change Name");
        changeUsernameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUsernameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TotalPromptsPannel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(TotalPromptsPannel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(TotalPromptsPannel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TotalPromptsPannel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vinilaRaceLabel1)
                                    .addComponent(vinilaRaceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TotalPromptsPannel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(TotalPromptsPannel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(TotalPromptsPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(44, 44, 44)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(changeUsernameButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(448, 448, 448)
                                    .addComponent(TotalPromptsPannel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TotalPromptsPannel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeUsernameButton)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TotalPromptsPannel, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalPromptsPannel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TotalPromptsPannel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(vinilaRaceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TotalPromptsPannel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TotalPromptsPannel3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vinilaRaceLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalPromptsPannel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalPromptsPannel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalPromptsPannel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalPromptsPannel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        saveButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jMenu1.add(saveButton);

        loadButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        jMenu1.add(loadButton);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        mw.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            try {
               pd = pd.loadPlayerData(f);
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Could not load from file \n" + 
                        f.getPath(), "Load failed", JOptionPane.ERROR_MESSAGE);
            }
        }
        updateAllData();
    }//GEN-LAST:event_loadButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
         int returnVal = chooser.showSaveDialog(this);
            if(returnVal == JFileChooser.APPROVE_OPTION) {
                File f = chooser.getSelectedFile();
                try {
                    System.out.println(f);
                    pd.SavePlayerData(f);
                } catch (IOException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Could not save to file \n" + 
                            f.getPath(), "Save failed", JOptionPane.ERROR_MESSAGE);
                }
            }   
    }//GEN-LAST:event_saveButtonActionPerformed

    private void changeUsernameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUsernameButtonActionPerformed
        String m = JOptionPane.showInputDialog(null, "What would you like to change your username to?", 
                "Change Username", JOptionPane.INFORMATION_MESSAGE);
        if(m.length() <= 14)
            pd.setUsername(m);
        else    
            JOptionPane.showMessageDialog(null, "Name must be less than 14 characters");
        
    }//GEN-LAST:event_changeUsernameButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvgSpeedLabel1;
    private javax.swing.JLabel AvgSpeedLabel2;
    private javax.swing.JLabel AvgSpeedLabel3;
    private javax.swing.JLabel AvgSpeedLabel4;
    private javax.swing.JLabel AvgSpeedLabel5;
    private javax.swing.JLabel AvgSpeedLabel6;
    private javax.swing.JPanel TotalPromptsPannel;
    private javax.swing.JPanel TotalPromptsPannel2;
    private javax.swing.JPanel TotalPromptsPannel3;
    private javax.swing.JPanel TotalPromptsPannel4;
    private javax.swing.JPanel TotalPromptsPannel5;
    private javax.swing.JPanel TotalPromptsPannel6;
    private javax.swing.JPanel TotalPromptsPannel7;
    private javax.swing.JPanel TotalPromptsPannel8;
    private javax.swing.JPanel TotalPromptsPannel9;
    private javax.swing.JLabel allTimeAvgErrors;
    private javax.swing.JLabel allTimeAvgLabel2;
    private javax.swing.JLabel allTimeAvgLabel3;
    private javax.swing.JLabel allTimeAvgWpm;
    private javax.swing.JLabel allTimeAvgWpmLabel;
    private javax.swing.JLabel allTimeFastest;
    private javax.swing.JLabel allTimePrompts;
    private javax.swing.JButton changeUsernameButton;
    private javax.swing.JLabel idAvgErrors;
    private javax.swing.JLabel idAvgSpeedLabel1;
    private javax.swing.JLabel idAvgWPM;
    private javax.swing.JLabel idFastestWPM;
    private javax.swing.JLabel idTotalPrompts;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private javax.swing.JMenuItem loadButton;
    private javax.swing.JMenuItem saveButton;
    private javax.swing.JLabel totalPrompts;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel vinilaRaceLabel;
    private javax.swing.JLabel vinilaRaceLabel1;
    private javax.swing.JLabel vrAvgErrors;
    private javax.swing.JLabel vrAvgSpeedLabel;
    private javax.swing.JLabel vrAvgWPM;
    private javax.swing.JLabel vrFastestWPM;
    private javax.swing.JLabel vrTotalPrompts;
    // End of variables declaration//GEN-END:variables
}
